# Generated by Django 4.0.5 on 2022-06-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.PositiveIntegerField(verbose_name='№')),
                ('order_number', models.PositiveIntegerField(verbose_name='заказ №')),
                ('cost_dollars', models.PositiveIntegerField(verbose_name='стоимость,$')),
                ('cost_rubles', models.PositiveIntegerField(verbose_name='стоимость в руб.')),
                ('delivery_time', models.DateField(verbose_name='срок поставки')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCurrencyWorker',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainapp.producttable',),
        ),
    ]
