# Generated by Django 4.0.5 on 2022-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrenciesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=10, verbose_name='Тикер валюты')),
                ('rate', models.FloatField(verbose_name='Значение относительно рубля')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductCurrencyWorker',
        ),
    ]
